#!/bin/bash

export TERM='xterm-256color'

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# COLORS: Determine whether we're live in technicolo(u)r
if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    technicolor=rainbow

    export CLICOLOR=1
    #export LSCOLORS=gxfxfxfxcxexexbxbxbxbx
    #COLOR_RED="\[\033[01;31m\]"
    #COLOR_GREEN="\[\033[01;32m\]"
    #COLOR_YELLOW="\[\033[01;33m\]"
    #COLOR_BLUE="\[\033[01;34m\]"
    #COLOR_PURPLE="\[\033[01;35m\]"
    #COLOR_CYAN="\[\033[01;36m\]"
    #COLOR_WHITE="\[\033[00m\]"
    COLOR_NONE='\[\033[00;0m\]'
    COLOR_RED='\[\033[00;31m\]'
    COLOR_GREEN='\[\033[00;32m\]'
    COLOR_YELLOW='\[\033[00;33m\]'
    COLOR_BLUE='\[\033[00;34m\]'
    COLOR_PURPLE='\[\033[00;35m\]'
    COLOR_CYAN='\[\033[00;36m\]'
    COLOR_GRAY='\[\033[00;37m\]'
    COLOR_LRED='\[\033[00;31m\]'
    COLOR_LGREEN='\[\033[00;32m\]'
    COLOR_LYELLOW='\[\033[00;33m\]'
    COLOR_LBLUE='\[\033[00;34m\]'
    COLOR_LPURPLE='\[\033[00;35m\]'
    COLOR_LCYAN='\[\033[00;36m\]'
    COLOR_WHITE='\[\033[00;37m\]'

else
# Actually, we prefer to trip the fuck out in old school black and white
    technicolor=
fi

# Normal user is purple, root is red.
if [ `id -u` == '0' ]; then
    USER_COLOR=$COLOR_RED
else
    USER_COLOR=$COLOR_LPURPLE
fi

# History
shopt -s histappend
shopt -s cmdhist

export HISTTIMEFORMAT="%T "
export HISTSIZE=""

function make_prompt {
    EXITSTATUS="$?"

    history -a

    if [[ $EXITSTATUS -eq 0 ]]
    then
        STATUS="${COLOR_GREEN}OK"
    else
        STATUS="${COLOR_RED}ERR ${EXITSTATUS}"
    fi

    VE_NAME=''
    if [ ${VIRTUAL_ENV} ]; then
        VE_NAME="${COLOR_CYAN}(`basename ${VIRTUAL_ENV}`) "
    fi

    VC_PROMPT=$(vcprompt -f "%n(%b)%u%m")

    PS1="${COLOR_PURPLE}[ \! ${STATUS} ${COLOR_GREEN}\u${COLOR_WHITE}@${COLOR_LPURPLE}\h${COLOR_WHITE}:${COLOR_BLUE}\w ${COLOR_YELLOW}${VE_NAME}${COLOR_RED}${VC_PROMPT}${COLOR_PURPLE} ]\n${COLOR_CYAN}\$ ${COLOR_NONE}"
    PS2=" > "
}


PROMPT_COMMAND=make_prompt

export PATH=$HOME/.cabal/bin:$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/local/lib:$PATH
export EDITOR="vim"

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
if [[ "$(uname)" == "Darwin" ]]; then
    alias ls='ls -G'
else
    alias ls='ls -G --color'
fi
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# global bash completion
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# local bash completion
for i in ~/.bash_completion.d/* ; do
    if [ -r "$i" ]; then
        . $i
    fi
done

if [ -d ${HOME}/.conf.d ]; then
    for conf in ${HOME}/.conf.d/*; do
        if [ -r "${conf}" ]; then
            . ${conf}
        fi
    done
fi

stty -ixon

now() {
    file="$HOME/.now"
    if [ ! -f $file ]; then
        touch $file;
    fi
    if [[ -z $@ ]]; then
        today="$(date "+%Y-%m-%d")"
        grep --color=never $today $file | cut -d' ' -f2-
    else
        stamp="$(date "+%Y-%m-%d %H:%M:%S")"
        echo $stamp - "$@" >> $file
    fi
}

eval $(keychain --eval -q)
