#!/bin/bash

#spawns
urxvtd -q -f -o &
xautolock -time 5 -locker "${HOME}/.screenlock.sh" -detectsleep &
eval `ssh-agent`
xmodmap ~/.Xmodmap
feh --no-fehbg --bg-max ~/background.png
xrdb -load ${HOME}/.Xresources
xset fp rehash
xsetroot -cursor_name  left_ptr
exec dbus-launch ssh-agent -- xmonad
