#!/bin/bash

#spawns
urxvtd -q -f -o &
xautolock -time 5 -locker "${HOME}/.screenlock.sh" -detectsleep &
eval $(cat ${HOME}/.fehbg)
eval $(ssh-agent -t 5h)
xmodmap ~/.Xmodmap
xrdb -load ${HOME}/.Xresources
xset fp rehash
xsetroot -cursor_name  left_ptr
/usr/local/bin/udiskie &
compton -b
exec dbus-run-session -- xmonad
