#!/bin/bash

export GOPATH=${HOME}
export PATH=${PATH}:${GOPATH}/bin
export GO15VENDOREXPERIMENT=1

gocd () {
    cd $(go list -f '{{.Dir}}' .../${1} | grep -v vendor | head -n 1)
}

rgocd () {
    cd $(go list -f '{{.Dir}}' ${1} | grep -v vendor | head -n 1)
}
